## Chronicle-Engine-GUI

********* THIS IS WORK IN PROGRESS  *********


// Settings:
:experimental:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// Aliases:
:project-name: Asciidoctor PDF
:project-handle: asciidoctor-pdf
 
toc::[]

a web based client management console to start the jetty application server, please 
[source, console]
----
mvn compile jetty:run
----

You fist have to start a chroncile engine, for example, go to the chronicle engine project and run
the main of :

Chronicle-Engine/src/main/java/net/openhft/chronicle/engine/StartEngineWithDummyData.java


then in you web-brower go to http://localhost:8080

the click log-in you should not have to fill in any details, just use the defauls.

then in your webbrowser fill in the the login form, providing the host:port of the server running
 chronicle-engine

###  vaadin-charts

WARNING: this project requires the following artifact
[source, console]
----
<dependency>
	<groupId>com.vaadin.addon</groupId>
	<artifactId>vaadin-charts</artifactId>
	<version>3.2.0</version>
</dependency>
----

A licenced version of this artifact can be obtained from https://vaadin.com/framework



