package net.openhft.chronicle.engine.gui;

import net.openhft.chronicle.core.Jvm;
import net.openhft.chronicle.engine.SimpleEngineMain;
import net.openhft.chronicle.engine.api.map.MapView;
import net.openhft.chronicle.engine.tree.VanillaAssetTree;

import java.io.IOException;

/**
 * @author Rob Austin.
 */
public class SimpleEngine {

    private static VanillaAssetTree ASSET_TREE = createEngine();

    public static VanillaAssetTree assetTree() {
        return ASSET_TREE;
    }

    private static VanillaAssetTree createEngine() {
        VanillaAssetTree assetTree = null;
        try {
            assetTree = SimpleEngineMain.tree();
        } catch (IOException e) {
            throw Jvm.rethrow(e);
        }

        MapView<String, String> mapView = assetTree.acquireMap("/my/demo", String.class, String.class);
        mapView.put("AED", "United Arab Emirates dirham");
        mapView.put("AFN", "Afghan afghani");
        mapView.put("ALL", "Albanian lek");
        mapView.put("AMD", "Armenian dram");
        mapView.put("ANG", "Netherlands Antillean guilder");
        mapView.put("AOA", "Angolan kwanza");
        mapView.put("ARS", "Argentine peso");
        mapView.put("AUD", "Australian dollar");
        mapView.put("AWG", "Aruban florin");
        mapView.put("AZN", "Azerbaijani manat");
        mapView.put("BAM", "Bosnia and Herzegovina convertible mark");
        mapView.put("BBD", "Barbados dollar");
        mapView.put("BDT", "Bangladeshi taka");
        mapView.put("BGN", "Bulgarian lev");
        mapView.put("BHD", "Bahraini dinar");
        mapView.put("BIF", "Burundian franc");
        mapView.put("BMD", "Bermudian dollar");
        mapView.put("BND", "Brunei dollar");
        mapView.put("BOB", "Boliviano");
        mapView.put("BOV", "Bolivian Mvdol (funds code)");
        mapView.put("BRL", "Brazilian real");
        mapView.put("BSD", "Bahamian dollar");
        mapView.put("BTN", "Bhutanese ngultrum");
        mapView.put("BWP", "Botswana pula");
        mapView.put("BYN", "Belarusian ruble");
        mapView.put("BYR", "Belarusian ruble");
        mapView.put("BZD", "Belize dollar");
        mapView.put("CAD", "Canadian dollar");
        mapView.put("CDF", "Congolese franc");
        mapView.put("CHE", "WIR Euro (complementary currency)");
        mapView.put("CHF", "Swiss franc");
        mapView.put("CHW", "WIR Franc (complementary currency)");
        mapView.put("CLF", "Unidad de Fomento (funds code)");
        mapView.put("CLP", "Chilean peso");
        mapView.put("CNY", "Chinese yuan");
        mapView.put("COP", "Colombian peso");
        mapView.put("COU", "Unidad de Valor Real (UVR) (funds code)[7]");
        mapView.put("CRC", "Costa Rican colon");
        mapView.put("CUC", "Cuban convertible peso");
        mapView.put("CUP", "Cuban peso");
        mapView.put("CVE", "Cape Verde escudo");
        mapView.put("CZK", "Czech koruna");
        mapView.put("DJF", "Djiboutian franc");
        mapView.put("DKK", "Danish krone");
        mapView.put("DOP", "Dominican peso");
        mapView.put("DZD", "Algerian dinar");
        mapView.put("EGP", "Egyptian pound");
        mapView.put("ERN", "Eritrean nakfa");
        mapView.put("ETB", "Ethiopian birr");
        mapView.put("EUR", "Euro");
        mapView.put("FJD", "Fiji dollar");
        mapView.put("FKP", "Falkland Islands pound");
        mapView.put("GBP", "Pound sterling");
        mapView.put("GEL", "Georgian lari");
        mapView.put("GHS", "Ghanaian cedi");
        mapView.put("GIP", "Gibraltar pound");
        mapView.put("GMD", "Gambian dalasi");
        mapView.put("GNF", "Guinean franc");
        mapView.put("GTQ", "Guatemalan quetzal");
        mapView.put("GYD", "Guyanese dollar");
        mapView.put("HKD", "Hong Kong dollar");
        mapView.put("HNL", "Honduran lempira");
        mapView.put("HRK", "Croatian kuna");
        mapView.put("HTG", "Haitian gourde");
        mapView.put("HUF", "Hungarian forint");
        mapView.put("IDR", "Indonesian rupiah");
        mapView.put("ILS", "Israeli new shekel");
        mapView.put("INR", "Indian rupee");
        mapView.put("IQD", "Iraqi dinar");
        mapView.put("IRR", "Iranian rial");
        mapView.put("ISK", "Icelandic króna");
        mapView.put("JMD", "Jamaican dollar");
        mapView.put("JOD", "Jordanian dinar");
        mapView.put("JPY", "Japanese yen");
        mapView.put("KES", "Kenyan shilling");
        mapView.put("KGS", "Kyrgyzstani som");
        mapView.put("KHR", "Cambodian riel");
        mapView.put("KMF", "Comoro franc");
        mapView.put("KPW", "North Korean won");
        mapView.put("KRW", "South Korean won");
        mapView.put("KWD", "Kuwaiti dinar");
        mapView.put("KYD", "Cayman Islands dollar");
        mapView.put("KZT", "Kazakhstani tenge");
        mapView.put("LAK", "Lao kip");
        mapView.put("LBP", "Lebanese pound");
        mapView.put("LKR", "Sri Lankan rupee");
        mapView.put("LRD", "Liberian dollar");
        mapView.put("LSL", "Lesotho loti");
        mapView.put("LYD", "Libyan dinar");
        mapView.put("MAD", "Moroccan dirham");
        mapView.put("MDL", "Moldovan leu");
        mapView.put("MGA", "Malagasy ariary");
        mapView.put("MKD", "Macedonian denar");
        mapView.put("MMK", "Myanmar kyat");
        mapView.put("MNT", "Mongolian tögrög");
        mapView.put("MOP", "Macanese pataca");
        mapView.put("MRO", "Mauritanian ouguiya");
        mapView.put("MUR", "Mauritian rupee");
        mapView.put("MVR", "Maldivian rufiyaa");
        mapView.put("MWK", "Malawian kwacha");
        mapView.put("MXN", "Mexican peso");
        mapView.put("MXV", "Mexican Unidad de Inversion (UDI) (funds code)");
        mapView.put("MYR", "Malaysian ringgit");
        mapView.put("MZN", "Mozambican metical");
        mapView.put("NAD", "Namibian dollar");
        mapView.put("NGN", "Nigerian naira");
        mapView.put("NIO", "Nicaraguan córdoba");
        mapView.put("NOK", "Norwegian krone");
        mapView.put("NPR", "Nepalese rupee");
        mapView.put("NZD", "New Zealand dollar");
        mapView.put("OMR", "Omani rial");
        mapView.put("PAB", "Panamanian balboa");
        mapView.put("PEN", "Peruvian Sol");
        mapView.put("PGK", "Papua New Guinean kina");
        mapView.put("PHP", "Philippine peso");
        mapView.put("PKR", "Pakistani rupee");
        mapView.put("PLN", "Polish złoty");
        mapView.put("PYG", "Paraguayan guaraní");
        mapView.put("QAR", "Qatari riyal");
        mapView.put("RON", "Romanian leu");
        mapView.put("RSD", "Serbian dinar");
        mapView.put("RUB", "Russian ruble");
        mapView.put("RWF", "Rwandan franc");
        mapView.put("SAR", "Saudi riyal");
        mapView.put("SBD", "Solomon Islands dollar");
        mapView.put("SCR", "Seychelles rupee");
        mapView.put("SDG", "Sudanese pound");
        mapView.put("SEK", "Swedish krona/kronor");
        mapView.put("SGD", "Singapore dollar");
        mapView.put("SHP", "Saint Helena pound");
        mapView.put("SLL", "Sierra Leonean leone");
        mapView.put("SOS", "Somali shilling");
        mapView.put("SRD", "Surinamese dollar");
        mapView.put("SSP", "South Sudanese pound");
        mapView.put("STD", "São Tomé and Príncipe dobra");
        mapView.put("SVC", "Salvadoran colón");
        mapView.put("SYP", "Syrian pound");
        mapView.put("SZL", "Swazi lilangeni");
        mapView.put("THB", "Thai baht");
        mapView.put("TJS", "Tajikistani somoni");
        mapView.put("TMT", "Turkmenistani manat");
        mapView.put("TND", "Tunisian dinar");
        mapView.put("TOP", "Tongan paʻanga");
        mapView.put("TRY", "Turkish lira");
        mapView.put("TTD", "Trinidad and Tobago dollar");
        mapView.put("TWD", "New Taiwan dollar");
        mapView.put("TZS", "Tanzanian shilling");
        mapView.put("UAH", "Ukrainian hryvnia");
        mapView.put("UGX", "Ugandan shilling");
        mapView.put("USD", "United States dollar");
        mapView.put("UYU", "Uruguayan peso");
        mapView.put("UZS", "Uzbekistan som");
        mapView.put("VEF", "Venezuelan bolívar");
        mapView.put("VND", "Vietnamese dong");
        mapView.put("VUV", "Vanuatu vatu");
        mapView.put("WST", "Samoan tala");
        mapView.put("XAF", "CFA franc BEAC");
        mapView.put("XCD", "East Caribbean dollar");
        mapView.put("XDR", "Special drawing rights");
        mapView.put("XOF", "CFA franc BCEAO");
        mapView.put("XPD", "Palladium (one troy ounce)");
        mapView.put("XPF", "CFP franc (franc Pacifique)");
        mapView.put("XPT", "Platinum (one troy ounce)");
        mapView.put("XSU", "SUCRE");
        mapView.put("XTS", "Code reserved for testing purposes");
        mapView.put("XUA", "ADB Unit of Account");
        mapView.put("XXX", "No currency");
        mapView.put("YER", "Yemeni rial");
        mapView.put("ZAR", "South African rand");
        mapView.put("ZMW", "Zambian kwacha");
        mapView.put("ZWL", "Zimbabwean dollar A/10");
        mapView.put("Code", "Currency");
        mapView.put("AED", "United Arab Emirates dirham");
        mapView.put("AFN", "Afghan afghani");
        mapView.put("ALL", "Albanian lek");
        mapView.put("AMD", "Armenian dram");
        mapView.put("ANG", "Netherlands Antillean guilder");
        mapView.put("AOA", "Angolan kwanza");
        mapView.put("ARS", "Argentine peso");
        mapView.put("AUD", "Australian dollar");
        mapView.put("AWG", "Aruban florin");
        mapView.put("AZN", "Azerbaijani manat");
        mapView.put("BAM", "Bosnia and Herzegovina convertible mark");
        mapView.put("BBD", "Barbados dollar");
        mapView.put("BDT", "Bangladeshi taka");
        mapView.put("BGN", "Bulgarian lev");
        mapView.put("BHD", "Bahraini dinar");
        mapView.put("BIF", "Burundian franc");
        mapView.put("BMD", "Bermudian dollar");
        mapView.put("BND", "Brunei dollar");
        mapView.put("BOB", "Boliviano");
        mapView.put("BOV", "Bolivian Mvdol (funds code)");
        mapView.put("BRL", "Brazilian real");
        mapView.put("BSD", "Bahamian dollar");
        mapView.put("BTN", "Bhutanese ngultrum");
        mapView.put("BWP", "Botswana pula");
        mapView.put("BYN", "Belarusian ruble");
        mapView.put("BYR", "Belarusian ruble");
        mapView.put("BZD", "Belize dollar");
        mapView.put("CAD", "Canadian dollar");
        mapView.put("CDF", "Congolese franc");
        mapView.put("CHF", "Swiss franc");
        mapView.put("CLP", "Chilean peso");
        mapView.put("CNY", "Chinese yuan");
        mapView.put("COP", "Colombian peso");
        mapView.put("CRC", "Costa Rican colon");
        mapView.put("CUC", "Cuban convertible peso");
        mapView.put("CUP", "Cuban peso");
        mapView.put("CVE", "Cape Verde escudo");
        mapView.put("CZK", "Czech koruna");
        mapView.put("DJF", "Djiboutian franc");
        mapView.put("DKK", "Danish krone");
        mapView.put("DOP", "Dominican peso");
        mapView.put("DZD", "Algerian dinar");
        mapView.put("EGP", "Egyptian pound");
        mapView.put("ERN", "Eritrean nakfa");
        mapView.put("ETB", "Ethiopian birr");
        mapView.put("EUR", "Euro");
        mapView.put("FJD", "Fiji dollar");
        mapView.put("FKP", "Falkland Islands pound");
        mapView.put("GBP", "Pound sterling");
        mapView.put("GEL", "Georgian lari");
        mapView.put("GHS", "Ghanaian cedi");
        mapView.put("GIP", "Gibraltar pound");
        mapView.put("GMD", "Gambian dalasi");
        mapView.put("GNF", "Guinean franc");
        mapView.put("GTQ", "Guatemalan quetzal");
        mapView.put("GYD", "Guyanese dollar");
        mapView.put("HKD", "Hong Kong dollar");
        mapView.put("HNL", "Honduran lempira");
        mapView.put("HRK", "Croatian kuna");
        mapView.put("HTG", "Haitian gourde");
        mapView.put("HUF", "Hungarian forint");
        mapView.put("IDR", "Indonesian rupiah");
        mapView.put("ILS", "Israeli new shekel");
        mapView.put("INR", "Indian rupee");
        mapView.put("IQD", "Iraqi dinar");
        mapView.put("IRR", "Iranian rial");
        mapView.put("ISK", "Icelandic króna");
        mapView.put("JMD", "Jamaican dollar");
        mapView.put("JOD", "Jordanian dinar");
        mapView.put("JPY", "Japanese yen");
        mapView.put("KES", "Kenyan shilling");
        mapView.put("KGS", "Kyrgyzstani som");
        mapView.put("KHR", "Cambodian riel");
        mapView.put("KMF", "Comoro franc");
        mapView.put("KPW", "North Korean won");
        mapView.put("KRW", "South Korean won");
        mapView.put("KWD", "Kuwaiti dinar");
        mapView.put("KYD", "Cayman Islands dollar");
        mapView.put("KZT", "Kazakhstani tenge");
        mapView.put("LAK", "Lao kip");
        mapView.put("LBP", "Lebanese pound");
        mapView.put("LKR", "Sri Lankan rupee");
        mapView.put("LRD", "Liberian dollar");
        mapView.put("LSL", "Lesotho loti");
        mapView.put("LYD", "Libyan dinar");
        mapView.put("MAD", "Moroccan dirham");
        mapView.put("MDL", "Moldovan leu");
        mapView.put("MGA", "Malagasy ariary");
        mapView.put("MKD", "Macedonian denar");
        mapView.put("MMK", "Myanmar kyat");
        mapView.put("MNT", "Mongolian tögrög");
        mapView.put("MOP", "Macanese pataca");
        mapView.put("MRO", "Mauritanian ouguiya");
        mapView.put("MUR", "Mauritian rupee");
        mapView.put("MVR", "Maldivian rufiyaa");
        mapView.put("MWK", "Malawian kwacha");
        mapView.put("MXN", "Mexican peso");
        mapView.put("MXV", "Mexican Unidad de Inversion (UDI) (funds code)");
        mapView.put("MYR", "Malaysian ringgit");
        mapView.put("MZN", "Mozambican metical");
        mapView.put("NAD", "Namibian dollar");
        mapView.put("NGN", "Nigerian naira");
        mapView.put("NIO", "Nicaraguan córdoba");
        mapView.put("NOK", "Norwegian krone");
        mapView.put("NPR", "Nepalese rupee");
        mapView.put("NZD", "New Zealand dollar");
        mapView.put("OMR", "Omani rial");
        mapView.put("PAB", "Panamanian balboa");
        mapView.put("PEN", "Peruvian Sol");
        mapView.put("PGK", "Papua New Guinean kina");
        mapView.put("PHP", "Philippine peso");
        mapView.put("PKR", "Pakistani rupee");
        mapView.put("PLN", "Polish złoty");
        mapView.put("PYG", "Paraguayan guaraní");
        mapView.put("QAR", "Qatari riyal");
        mapView.put("RON", "Romanian leu");
        mapView.put("RSD", "Serbian dinar");
        mapView.put("RUB", "Russian ruble");
        mapView.put("RWF", "Rwandan franc");
        mapView.put("SAR", "Saudi riyal");
        mapView.put("SBD", "Solomon Islands dollar");
        mapView.put("SCR", "Seychelles rupee");
        mapView.put("SDG", "Sudanese pound");
        mapView.put("SEK", "Swedish krona/kronor");
        mapView.put("SGD", "Singapore dollar");
        mapView.put("SHP", "Saint Helena pound");
        mapView.put("SLL", "Sierra Leonean leone");
        mapView.put("SOS", "Somali shilling");
        mapView.put("SRD", "Surinamese dollar");
        mapView.put("SSP", "South Sudanese pound");
        mapView.put("STD", "São Tomé and Príncipe dobra");
        mapView.put("SVC", "Salvadoran colón");
        mapView.put("SYP", "Syrian pound");
        mapView.put("SZL", "Swazi lilangeni");
        mapView.put("THB", "Thai baht");
        mapView.put("TJS", "Tajikistani somoni");
        mapView.put("TMT", "Turkmenistani manat");
        mapView.put("TND", "Tunisian dinar");
        mapView.put("TOP", "Tongan paʻanga");
        mapView.put("TRY", "Turkish lira");
        mapView.put("TTD", "Trinidad and Tobago dollar");
        mapView.put("TWD", "New Taiwan dollar");
        mapView.put("TZS", "Tanzanian shilling");
        mapView.put("UAH", "Ukrainian hryvnia");
        mapView.put("UGX", "Ugandan shilling");
        mapView.put("USD", "United States dollar");
        mapView.put("UYI", "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)");
        mapView.put("UYU", "Uruguayan peso");
        mapView.put("UZS", "Uzbekistan som");
        mapView.put("VEF", "Venezuelan bolívar");
        mapView.put("VND", "Vietnamese dong");
        mapView.put("VUV", "Vanuatu vatu");
        mapView.put("WST", "Samoan tala");
        mapView.put("XAF", "CFA franc BEAC");
        mapView.put("XAG", "Silver (one troy ounce)");
        return assetTree;
    }

}
